on: [push]

jobs:
  run_tests_php56:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run tests with php 5.6
        run: docker-compose run --rm tests-php-5.6
  run_tests_php71:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run tests with php 7.1
        run: docker-compose run --rm tests-php-7.1
